name: Update Hugo Template for GTS
on: 
  workflow_call:
  workflow_dispatch:
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make body font color black
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "--MAIN-TEXT-color:#323235;"
          replace: "--MAIN-TEXT-color:#000000;"
          include: "static/css/theme-mine.css"
          regex: false

      - name: Create custom_header.html if not found
        run: |
          ls layouts/partials/custom_header.html 2&>/dev/null || cat <<EOF > layouts/partials/custom_header.html
          #cat <<EOF > layouts/partials/custom_header.html
          <script defer language="javascript" type="text/javascript"  src="{{ "/js/gts_hugo.js" | urlize | relURL }}"></script>
          <script>
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-TZFSQDF');
          </script>
          EOF

      - name: Remove padding in body
        run: |
          grep -qxF '#body .padding {padding: 1rem 3rem;}' static/css/theme-mine.css || echo '
          #body .padding {padding: 1rem 3rem;}' >> static/css/theme-mine.css

      - name: Remove padding in chapter
        run: |
          grep -qxF '#chapter {padding: 0 0 4rem 0;}' static/css/theme-mine.css || echo '   
          #chapter {padding: 0 0 4rem 0;}' >> static/css/theme-mine.css
      
      - name: Remove Menu shortcuts
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "(?m)(\\[\\[menu\\.shortcuts\\]\\](.*\n)+?)(^weight = .*)"
          replace: " "
          include: "config.toml"
          regex: true

      - name: Remove Languages shortcuts
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "(?m)(\\[Languages(.*\n)+?)(^languageName = .*)"
          replace: " "
          include: "config.toml"
          regex: true

      - name: Add popups to links
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "(href=\"https:([^\"]+?\"))(>.*)"
          replace: "$1 target=\"_blank\"$3"
          include: "layouts/partials/menu-footer.html"
          regex: true

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: GHA Auto-Update Template for GTS
